sudo: required
language: ruby
rvm:
  - 2.0.0
  - 2.4.1

before_install:
  # https://launchpad.net/~pi-rho/+archive/ubuntu/dev
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:pi-rho/dev
  - sudo apt-get update
  - sudo apt-get install -y tmux-next=2.3~20170701~bzr3917+20-1ubuntu1~ppa0~ubuntu12.04.1
  - sudo ln -sf /usr/bin/tmux-next /usr/bin/tmux
  - gem install bundler -v 1.15.1

script: |
  tmux new "rake test > out && touch ok" && cat out && [ -e ok ]
